[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = "0.11.1"
http = "0.2.9"
lambda_http = "0.8.1"
log = "0.4.20"
simple_logger = "4.2.0"
tokio = "1.32.0"
